name: price-monitor-interactive

on:
  schedule:
    - cron: '0 * * * *'   # cada hora en punto (UTC)
  workflow_dispatch:       # permite ejecutarlo manualmente

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monitor (genera docs/dashboard.html)
        run: |
          python src/monitor_plotly.py --config src/config.yaml

      - name: Commit changes (data + dashboard)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: hourly update (data + dashboard) [skip ci]" || echo "no changes"
          git push
