name: price-monitor-interactive

on:
  schedule:
    - cron: "*/30 * * * *"     # cada 30 minutos
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run monitor (genera docs/dashboard.html)
        run: |
          python src/monitor_plotly.py --config src/config.yaml

      - name: Commit changes (data + dashboard)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: update data and dashboard [skip ci]" || echo "no changes"
          git push
